version: '3'
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
      MONGO_INITDB_DATABASE: sleeper
    container_name: mongodb_sleeper
    volumes:
      - 'mongodb:/data/db'
    ports:
      - '27017:27017'
volumes:
  mongodb: